// Actions types

export const MAKE_REQUEST = 'MAKE_REQUEST';
export const FAIL_REQUEST = 'FAIL_REQUEST';

export const REGISTER_USER = 'SAVE_USER';
export const LOGIN = 'LOGIN';
export const SET_USER = 'SET_USER';

export const START_EVENT = 'START_EVENT';
export const SAVE_EVENT = 'SAVE_EVENT';
export const FAIL_EVENT = 'FAIL_EVENT';
export const SET_EVENT = 'SET_EVENT';
export const SET_USER_EVENTS = 'SET_USER_EVENTS';

export const POPULATE_CATEGORIES = 'POPULATE_CATEGORIES';
export const POPULATE_TYPES = 'POPULATE_TYPES';
export const POPULATE_RESTRICTIONS = 'POPULATE_RESTRICTIONS';
export const POPULATE_MODALITY = 'POPULATE_MODALITY';
export const POPULATE_COUNTRIES = 'POPULATE_COUNTRIES';
