// Actions types

export const MAKE_REQUEST = 'MAKE_REQUEST';
export const FAIL_REQUEST = 'FAIL_REQUEST';

export const REGISTER_USER = 'SAVE_USER';
export const LOGIN = 'LOGIN';
export const SET_USER = 'SET_USER';

export const START_EVENT = 'START_EVENT';
export const SAVE_EVENT = 'SAVE_EVENT';
export const FAIL_EVENT = 'FAIL_EVENT';
export const SET_EVENT = 'SET_EVENT';
export const SET_USER_EVENTS = 'SET_USER_EVENTS';
export const ST_GET_EVENT_GUESTS = 'ST_GET_EVENT_GUESTS';
export const FL_GET_EVENT_GUESTS = 'FL_GET_EVENT_GUESTS';
export const SUC_GET_EVENT_GUESTS = 'SUC_GET_EVENT_GUESTS';
export const EVENT_PUBLISHED = 'EVENT_PUBLISHED';
export const ST_GET_EVENTS_PUBLISHED = 'ST_GET_EVENTS_PUBLISHED';
export const GET_EVENTS_PUBLISHED = 'GET_EVENTS_PUBLISHED';
export const ST_SUB_USER_IN_EVENT = 'ST_SUB_USER_IN_EVENT';
export const USER_SUBSCRIBED = 'USER_SUBSCRIBED';
export const ST_COPY_EVENT = 'ST_COPY_EVENT';
export const EVENT_COPIED = 'EVENT_COPIED';

export const POPULATE_CATEGORIES = 'POPULATE_CATEGORIES';
export const POPULATE_TYPES = 'POPULATE_TYPES';
export const POPULATE_RESTRICTIONS = 'POPULATE_RESTRICTIONS';
export const POPULATE_MODALITY = 'POPULATE_MODALITY';
export const POPULATE_COUNTRIES = 'POPULATE_COUNTRIES';
export const POPULATE_STATES = 'POPULATE_STATES';
export const POPULATE_GENRES = 'POPULATE_GENRES';

export const ST_UPDATE_USER = 'ST_UPDATE_USER';
export const FL_UPDATE_USER = 'FL_UPDATE_USER';
export const SUC_UPDATE_USER = 'SUC_UPDATE_USER';
export const ST_GET_USER = 'ST_GET_USER';
export const USER_FETCHED = 'USER_FETCHED';

export const CREATE_DRAFT_PIN = 'CREATE_DRAFT_PIN';
export const UPDATE_DRAFT_PIN_LOCATION = 'UPDATE_DRAFT_PIN_LOCATION';
export const GET_EVENT_PINS = 'GET_EVENT_PINS';
export const DELETE_DRAFT_PIN_LOCATION = 'DELETE_DRAFT_PIN_LOCATION';
export const CLEAR_EVENT_PINS = 'CLEAR_EVENT_PINS';
export const SET_CURRENT_PIN = 'SET_CURRENT_PIN';
